### ISSUE TITLE
Comment in Italic not working

### ISSUE THREAD

**Issue by 4goodapp** [tompave/rails_base_16#1]
In Sublime Text, comments dont show in Italic style

And here http://i.cubeupload.com/JIy3jJ.png , I think that Article's methodes like _new _, _all _, and _find _shoul have the same co

**Comment by tompave** [comment]
Apologies, I've just seen this.

The link doesn't work anymore. Is this still an issue?

**Comment by tompave** [comment]
Closing as too old.
